#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Plot metric bar charts from existing average_metrics_full.json.
This script reads the JSON file generated by evaluate_full.py and produces
bar charts for PSNR, SSIM, LPIPS, tLPIPS, and FID (if available).
"""

import json
import os
import matplotlib.pyplot as plt
import numpy as np

def load_metrics(json_path):
    """Load average metrics from JSON file."""
    with open(json_path, 'r') as f:
        data = json.load(f)
    # data is a list of dicts, each with 'method', 'avg_avg_psnr', 'std_avg_psnr', etc.
    return data

def save_bar_chart(data_dict, metric_name, ylabel, title, output_path, ylim=None, higher_better=True):
    """
    Save a bar chart of metric values for different methods.
    data_dict: {method_name: value}
    metric_name: string for display
    higher_better: if True, sort descending; if False, sort ascending (for LPIPS/tLPIPS/FID)
    """
    methods = list(data_dict.keys())
    values = list(data_dict.values())
    
    # Sort: for higher_better -> descending; for lower better -> ascending (so best on left)
    if higher_better:
        sorted_pairs = sorted(zip(methods, values), key=lambda x: x[1], reverse=True)
    else:
        sorted_pairs = sorted(zip(methods, values), key=lambda x: x[1])  # lowest first
    
    methods_sorted = [p[0] for p in sorted_pairs]
    values_sorted = [p[1] for p in sorted_pairs]
    
    plt.figure(figsize=(12, 6))
    bars = plt.bar(methods_sorted, values_sorted, color='skyblue', edgecolor='black')
    plt.ylabel(ylabel, fontsize=12)
    plt.title(title, fontsize=14)
    plt.xticks(rotation=45, ha='right', fontsize=10)
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    if ylim:
        plt.ylim(ylim)
    
    # Add value labels on top of bars
    for bar, val in zip(bars, values_sorted):
        offset = max(values_sorted) * 0.02 if max(values_sorted) > 0 else 0.02
        plt.text(bar.get_x() + bar.get_width()/2, bar.get_height() + offset,
                 f'{val:.3f}', ha='center', va='bottom', fontsize=9)
    
    plt.tight_layout()
    plt.savefig(output_path, dpi=150)
    plt.close()
    print(f"Saved {metric_name} chart to {output_path}")

def main():
    # ========== CONFIGURATION ==========
    # Path to your average_metrics_full.json (generated by evaluate_full.py)
    json_path = "outputs/average_metrics_full.json"   # <-- CHANGE THIS IF NEEDED
    output_dir = "outputs"                             # where to save charts
    
    # ========== LOAD DATA ==========
    if not os.path.exists(json_path):
        print(f"Error: {json_path} not found. Please adjust the path.")
        return
    
    data = load_metrics(json_path)
    if not data:
        print("No data found in JSON.")
        return
    
    # Extract method names
    methods = [entry['method'] for entry in data]
    
    # ----- PSNR -----
    if 'avg_avg_psnr' in data[0]:
        psnr_dict = {entry['method']: entry['avg_avg_psnr'] for entry in data}
        save_bar_chart(psnr_dict, 'PSNR', 'PSNR (dB)', 'Average PSNR across videos',
                       os.path.join(output_dir, 'psnr_comparison.png'),
                       ylim=(0, 40), higher_better=True)
    
    # ----- SSIM -----
    if 'avg_avg_ssim' in data[0]:
        ssim_dict = {entry['method']: entry['avg_avg_ssim'] for entry in data}
        save_bar_chart(ssim_dict, 'SSIM', 'SSIM', 'Average SSIM across videos',
                       os.path.join(output_dir, 'ssim_comparison.png'),
                       ylim=(0, 1), higher_better=True)
    
    # ----- LPIPS (lower better) -----
    if 'avg_avg_lpips' in data[0]:
        lpips_dict = {entry['method']: entry['avg_avg_lpips'] for entry in data}
        save_bar_chart(lpips_dict, 'LPIPS', 'LPIPS (lower better)', 'Average LPIPS across videos',
                       os.path.join(output_dir, 'lpips_comparison.png'),
                       ylim=(0, 1), higher_better=False)
    
    # ----- tLPIPS (lower better) -----
    if 'avg_tlpips' in data[0]:
        tlpips_dict = {entry['method']: entry['avg_tlpips'] for entry in data}
        save_bar_chart(tlpips_dict, 'tLPIPS', 'tLPIPS (lower better)', 'Average tLPIPS across videos',
                       os.path.join(output_dir, 'tlpips_comparison.png'),
                       ylim=(0, 1), higher_better=False)
    
    # ----- FID (lower better) -----
    if 'avg_fid' in data[0]:
        fid_dict = {entry['method']: entry['avg_fid'] for entry in data}
        save_bar_chart(fid_dict, 'FID', 'FID (lower better)', 'Average FID across videos',
                       os.path.join(output_dir, 'fid_comparison.png'),
                       ylim=None, higher_better=False)
    
    print("\nAll available charts have been generated.")

if __name__ == '__main__':
    main()